CREATE FUNCTION [wct].[ADJCURRYIELD]
(@Settlement DATETIME, @Maturity DATETIME, @Price FLOAT (53), @Rate FLOAT (53), @Basis NVARCHAR (4000))
RETURNS FLOAT (53)
AS
 EXTERNAL NAME [XLeratorDB_suitePLUS2008].[XLeratorDB_suitePLUS2008.UserDefinedFunctions].[ADJCURRYIELD]

