CREATE FUNCTION [wct].[BETADIST]
(@X FLOAT (53), @P FLOAT (53), @Q FLOAT (53), @A FLOAT (53), @B FLOAT (53))
RETURNS FLOAT (53)
AS
 EXTERNAL NAME [XLeratorDB_suitePLUS2008].[XLeratorDB_suitePLUS2008.UserDefinedFunctions].[BETADIST]

