CREATE FUNCTION [wct].[BUSDAYSWE]
(@StartDate DATETIME, @EndDate DATETIME, @Holidays NVARCHAR (MAX), @WE1 INT, @WE2 INT)
RETURNS INT
AS
 EXTERNAL NAME [XLeratorDB_suitePLUS2008].[XLeratorDB_suitePLUS2008.UserDefinedFunctions].[BUSDAYSWE]

