CREATE FUNCTION [wct].[BUSINESSDATE]
(@StartDate DATETIME, @DatePart NVARCHAR (4000), @Number INT, @DateRollRule NVARCHAR (4000), @Holidays NVARCHAR (MAX))
RETURNS DATETIME
AS
 EXTERNAL NAME [XLeratorDB_suitePLUS2008].[XLeratorDB_suitePLUS2008.UserDefinedFunctions].[BUSINESSDATE]

