CREATE FUNCTION [wct].[CONCAT]
(@Text1 NVARCHAR (MAX), @Joiner NVARCHAR (MAX), @Text2 NVARCHAR (MAX))
RETURNS NVARCHAR (MAX)
AS
 EXTERNAL NAME [XLeratorDB_suitePLUS2008].[XLeratorDB_suitePLUS2008.UserDefinedFunctions].[CONCAT]

