CREATE AGGREGATE [wct].[DFINTERP](@DFdate DATETIME, @DF FLOAT (53), @NewDate DATETIME, @StartDate DATETIME, @RV NVARCHAR (4000))
    RETURNS FLOAT (53)
    EXTERNAL NAME [XLeratorDB_suitePLUS2008].[XLeratorDB_suitePLUS2008.DFINTERP];

