CREATE AGGREGATE [wct].[EQVOLATILITY](@PDate DATETIME, @PValue FLOAT (53), @Scale FLOAT (53))
    RETURNS FLOAT (53)
    EXTERNAL NAME [XLeratorDB_suitePLUS2008].[XLeratorDB_suitePLUS2008.EQVOLATILITY];

