CREATE FUNCTION [wct].[FORMATDATE]
(@Value DATETIME, @Format NVARCHAR (4000))
RETURNS NVARCHAR (4000)
AS
 EXTERNAL NAME [XLeratorDB_suitePLUS2008].[XLeratorDB_suitePLUS2008.UserDefinedFunctions].[FORMATDATE]

