CREATE FUNCTION [wct].[HEX2OCT]
(@Number NVARCHAR (4000), @Places FLOAT (53))
RETURNS NVARCHAR (4000)
AS
 EXTERNAL NAME [XLeratorDB_suitePLUS2008].[XLeratorDB_suitePLUS2008.UserDefinedFunctions].[HEX2OCT]

