CREATE FUNCTION [wct].[IMPOWER]
(@inumber NVARCHAR (4000), @Number FLOAT (53))
RETURNS NVARCHAR (4000)
AS
 EXTERNAL NAME [XLeratorDB_suitePLUS2008].[XLeratorDB_suitePLUS2008.UserDefinedFunctions].[IMPOWER]

