CREATE AGGREGATE [wct].[INFORATIO](@R FLOAT (53), @RB FLOAT (53), @Scale FLOAT (53), @Geometric BIT)
    RETURNS FLOAT (53)
    EXTERNAL NAME [XLeratorDB_suitePLUS2008].[XLeratorDB_suitePLUS2008.INFORATIO];

