CREATE AGGREGATE [wct].[INTERP2](@X FLOAT (53), @Y FLOAT (53), @Z FLOAT (53), @New_x FLOAT (53), @New_y FLOAT (53))
    RETURNS FLOAT (53)
    EXTERNAL NAME [XLeratorDB_suitePLUS2008].[XLeratorDB_suitePLUS2008.INTERP2];

