CREATE FUNCTION [wct].[KAPPA_COHEN]
(@InputData_RangeQuery NVARCHAR (MAX), @RV NVARCHAR (4000), @Weighting NVARCHAR (4000))
RETURNS FLOAT (53)
AS
 EXTERNAL NAME [XLeratorDB_suitePLUS2008].[XLeratorDB_suitePLUS2008.UserDefinedFunctions].[KAPPA_COHEN]

