CREATE FUNCTION [wct].[KENDALLW]
(@InputData_RangeQuery NVARCHAR (MAX), @CorrectTies BIT, @RV NVARCHAR (4000))
RETURNS FLOAT (53)
AS
 EXTERNAL NAME [XLeratorDB_suitePLUS2008].[XLeratorDB_suitePLUS2008.UserDefinedFunctions].[KENDALLW]

