CREATE FUNCTION [wct].[LASTWEEKDAY]
(@StartDate DATETIME, @DayofWeek NVARCHAR (4000))
RETURNS DATETIME
AS
 EXTERNAL NAME [XLeratorDB_suitePLUS2008].[XLeratorDB_suitePLUS2008.UserDefinedFunctions].[LASTWEEKDAY]

