CREATE FUNCTION [wct].[LOGITPRED]
(@B NVARCHAR (MAX), @New_x NVARCHAR (MAX))
RETURNS FLOAT (53)
AS
 EXTERNAL NAME [XLeratorDB_suitePLUS2008].[XLeratorDB_suitePLUS2008.UserDefinedFunctions].[LOGITPRED]

