CREATE FUNCTION [wct].[LOGISTIC]
(@X FLOAT (53), @A FLOAT (53), @B FLOAT (53), @Cumulative BIT)
RETURNS FLOAT (53)
AS
 EXTERNAL NAME [XLeratorDB_suitePLUS2008].[XLeratorDB_suitePLUS2008.UserDefinedFunctions].[LOGISTIC]

