CREATE FUNCTION [wct].[MATADD]
(@Matrix1 NVARCHAR (MAX), @Matrix2 NVARCHAR (MAX))
RETURNS NVARCHAR (MAX)
AS
 EXTERNAL NAME [XLeratorDB_suitePLUS2008].[XLeratorDB_suitePLUS2008.UserDefinedFunctions].[MATADD]

