CREATE FUNCTION [wct].[MNORM]
(@Matrix NVARCHAR (MAX), @NormType NVARCHAR (4000))
RETURNS FLOAT (53)
AS
 EXTERNAL NAME [XLeratorDB_suitePLUS2008].[XLeratorDB_suitePLUS2008.UserDefinedFunctions].[MNORM]

