CREATE FUNCTION [wct].[NCTCDF]
(@X FLOAT (53), @DF FLOAT (53), @Delta FLOAT (53))
RETURNS FLOAT (53)
AS
 EXTERNAL NAME [XLeratorDB_suitePLUS2008].[XLeratorDB_suitePLUS2008.UserDefinedFunctions].[NCTCDF]

