CREATE FUNCTION [wct].[NUMWORDS]
(@Text NVARCHAR (MAX), @Delimiters NVARCHAR (4000))
RETURNS INT
AS
 EXTERNAL NAME [XLeratorDB_suitePLUS2008].[XLeratorDB_suitePLUS2008.UserDefinedFunctions].[NUMWORDS]

