CREATE FUNCTION [wct].[OCT2BIN]
(@Number NVARCHAR (4000), @Places FLOAT (53))
RETURNS NVARCHAR (4000)
AS
 EXTERNAL NAME [XLeratorDB_suitePLUS2008].[XLeratorDB_suitePLUS2008.UserDefinedFunctions].[OCT2BIN]

