CREATE FUNCTION [wct].[ODDFPPMT]
(@Rate FLOAT (53), @Per INT, @Nper INT, @PV FLOAT (53), @FV FLOAT (53), @FirstPeriod FLOAT (53))
RETURNS FLOAT (53)
AS
 EXTERNAL NAME [XLeratorDB_suitePLUS2008].[XLeratorDB_suitePLUS2008.UserDefinedFunctions].[ODDFPPMT]

