CREATE FUNCTION [wct].[PDURATION]
(@Rate FLOAT (53), @PV FLOAT (53), @FV FLOAT (53))
RETURNS FLOAT (53)
AS
 EXTERNAL NAME [XLeratorDB_suitePLUS2008].[XLeratorDB_suitePLUS2008.UserDefinedFunctions].[PDURATION]

