CREATE AGGREGATE [wct].[POLYCOEF](@known_x FLOAT (53), @known_y FLOAT (53), @degree SMALLINT, @n SMALLINT)
    RETURNS FLOAT (53)
    EXTERNAL NAME [XLeratorDB_suitePLUS2008].[XLeratorDB_suitePLUS2008.POLYCOEF];

