CREATE FUNCTION [wct].[PSIGNRANK]
(@X FLOAT (53), @N FLOAT (53), @Exact BIT)
RETURNS FLOAT (53)
AS
 EXTERNAL NAME [XLeratorDB_suitePLUS2008].[XLeratorDB_suitePLUS2008.UserDefinedFunctions].[PSIGNRANK]

