CREATE FUNCTION [wct].[QR]
(@Matrix NVARCHAR (MAX), @MatrixName NVARCHAR (4000))
RETURNS NVARCHAR (MAX)
AS
 EXTERNAL NAME [XLeratorDB_suitePLUS2008].[XLeratorDB_suitePLUS2008.UserDefinedFunctions].[QR]

