CREATE FUNCTION [wct].[QUADDE]
(@Func NVARCHAR (MAX), @VarName NVARCHAR (4000), @A SQL_VARIANT, @B SQL_VARIANT)
RETURNS FLOAT (53)
AS
 EXTERNAL NAME [XLeratorDB_suitePLUS2008].[XLeratorDB_suitePLUS2008.UserDefinedFunctions].[QUADDE]

