CREATE FUNCTION [wct].[QUADOSC]
(@Func NVARCHAR (MAX), @VarName NVARCHAR (4000), @A SQL_VARIANT, @B SQL_VARIANT, @Omega FLOAT (53))
RETURNS FLOAT (53)
AS
 EXTERNAL NAME [XLeratorDB_suitePLUS2008].[XLeratorDB_suitePLUS2008.UserDefinedFunctions].[QUADOSC]

