CREATE FUNCTION [wct].[R78REBATE]
(@IntAmt FLOAT (53), @NumPmts INT, @PeriodNo INT)
RETURNS FLOAT (53)
AS
 EXTERNAL NAME [XLeratorDB_suitePLUS2008].[XLeratorDB_suitePLUS2008.UserDefinedFunctions].[R78REBATE]

