CREATE FUNCTION [wct].[SPEARMAN]
(@x_y_Query NVARCHAR (MAX), @RV NVARCHAR (4000))
RETURNS FLOAT (53)
AS
 EXTERNAL NAME [XLeratorDB_suitePLUS2008].[XLeratorDB_suitePLUS2008.UserDefinedFunctions].[SPEARMAN]

