CREATE FUNCTION [wct].[TBILLYIELD]
(@Settlement DATETIME, @Maturity DATETIME, @Pr FLOAT (53))
RETURNS FLOAT (53)
AS
 EXTERNAL NAME [XLeratorDB_suitePLUS2008].[XLeratorDB_suitePLUS2008.UserDefinedFunctions].[TBILLYIELD]

