CREATE FUNCTION [wct].[TENOR2DATE]
(@Tenor NVARCHAR (4000), @StartDate DATETIME, @SpotDate DATETIME, @Holidays NVARCHAR (MAX))
RETURNS DATETIME
AS
 EXTERNAL NAME [XLeratorDB_suitePLUS2008].[XLeratorDB_suitePLUS2008.UserDefinedFunctions].[TENOR2DATE]

