CREATE AGGREGATE [wct].[TTEST_PAIRED](@X1 FLOAT (53), @X2 FLOAT (53), @Statistic NVARCHAR (4000))
    RETURNS FLOAT (53)
    EXTERNAL NAME [XLeratorDB_suitePLUS2008].[XLeratorDB_suitePLUS2008.TTEST_PAIRED];

