CREATE FUNCTION [wct].[UNIFORMINV]
(@P FLOAT (53), @Min FLOAT (53), @Max FLOAT (53))
RETURNS FLOAT (53)
AS
 EXTERNAL NAME [XLeratorDB_suitePLUS2008].[XLeratorDB_suitePLUS2008.UserDefinedFunctions].[UNIFORMINV]

