CREATE FUNCTION [wct].[WMPSR]
(@InputData_RangeQuery NVARCHAR (MAX), @RV NVARCHAR (4000))
RETURNS FLOAT (53)
AS
 EXTERNAL NAME [XLeratorDB_suitePLUS2008].[XLeratorDB_suitePLUS2008.UserDefinedFunctions].[WMPSR]

