CREATE TABLE [dbo].[cor_useraccount] (
    [UserAccountId]          INT                IDENTITY (1, 1) NOT NULL,
    [StaffId]                INT                NOT NULL,
    [UserName]               VARCHAR (256)      NOT NULL,
    [Email]                  NVARCHAR (256)     NOT NULL,
    [EmailConfirmed]         BIT                NULL,
    [PasswordHash]           VARBINARY (MAX)    NULL,
    [PasswordSalt]           VARBINARY (MAX)    NULL,
    [PhoneNumber]            VARCHAR (MAX)      NULL,
    [PhoneNumberConfirmed]   BIT                NULL,
    [TwoFactorEnabled]       BIT                NOT NULL,
    [LockoutEnd]             DATETIMEOFFSET (7) NULL,
    [LockoutEnabled]         BIT                NULL,
    [AccessFailedCount]      INT                NOT NULL,
    [IsFirstLoginAttempt]    BIT                NOT NULL,
    [SecurityQuestion]       VARCHAR (256)      NULL,
    [SecurityAnswer]         VARCHAR (256)      NULL,
    [NextPasswordChangeDate] DATETIME           NULL,
    [IsActive]               BIT                NOT NULL,
    [LastLoginDate]          DATETIME           NULL,
    [Active]                 BIT                NULL,
    [Deleted]                BIT                NULL,
    [CreatedBy]              VARCHAR (50)       NULL,
    [CreatedOn]              DATETIME           NULL,
    [UpdatedBy]              VARCHAR (50)       NULL,
    [UpdatedOn]              DATETIME           NULL,
    CONSTRAINT [PK_cor_useraccount] PRIMARY KEY CLUSTERED ([UserAccountId] ASC),
    CONSTRAINT [FK_cor_useraccount_cor_staff] FOREIGN KEY ([StaffId]) REFERENCES [dbo].[cor_staff] ([StaffId])
);

