CREATE TABLE [dbo].[cor_approvaltrail] (
    [ApprovalTrailId]     INT           IDENTITY (1, 1) NOT NULL,
    [TargetId]            INT           NOT NULL,
    [OperationId]         INT           NOT NULL,
    [FromApprovalLevelId] INT           NULL,
    [ToApprovalLevelId]   INT           NULL,
    [ApprovalStatusId]    INT           NOT NULL,
    [RequestStaffId]      INT           NOT NULL,
    [ResponseStaffId]     INT           NULL,
    [ArrivalDate]         DATETIME      NOT NULL,
    [ResponseDate]        DATETIME      NULL,
    [CompanyId]           INT           NOT NULL,
    [Comment]             VARCHAR (MAX) NULL,
    [Active]              BIT           NULL,
    [Deleted]             BIT           NULL,
    [CreatedBy]           VARCHAR (50)  NULL,
    [CreatedOn]           DATETIME      NULL,
    [UpdatedBy]           VARCHAR (50)  NULL,
    [UpdatedOn]           DATETIME      NULL,
    CONSTRAINT [PK_cor_approvaltrail] PRIMARY KEY CLUSTERED ([ApprovalTrailId] ASC),
    CONSTRAINT [FK_cor_approvaltrail_cor_approvallevel] FOREIGN KEY ([FromApprovalLevelId]) REFERENCES [dbo].[cor_approvallevel] ([ApprovalLevelId]),
    CONSTRAINT [FK_cor_approvaltrail_cor_approvallevel1] FOREIGN KEY ([ToApprovalLevelId]) REFERENCES [dbo].[cor_approvallevel] ([ApprovalLevelId]),
    CONSTRAINT [FK_cor_approvaltrail_cor_approvalstatus] FOREIGN KEY ([ApprovalStatusId]) REFERENCES [dbo].[cor_approvalstatus] ([ApprovalStatusId]),
    CONSTRAINT [FK_cor_approvaltrail_cor_company] FOREIGN KEY ([CompanyId]) REFERENCES [dbo].[cor_company] ([CompanyId]),
    CONSTRAINT [FK_cor_approvaltrail_cor_operation] FOREIGN KEY ([OperationId]) REFERENCES [dbo].[cor_operation] ([OperationId]),
    CONSTRAINT [FK_cor_approvaltrail_cor_staff] FOREIGN KEY ([RequestStaffId]) REFERENCES [dbo].[cor_staff] ([StaffId]),
    CONSTRAINT [FK_cor_approvaltrail_cor_staff1] FOREIGN KEY ([ResponseStaffId]) REFERENCES [dbo].[cor_staff] ([StaffId])
);

