CREATE TABLE [dbo].[cor_workflowtrail] (
    [WorkflowTrailId]     INT           IDENTITY (1, 1) NOT NULL,
    [TargetId]            INT           NOT NULL,
    [OperationId]         INT           NOT NULL,
    [WorkflowId]          INT           NOT NULL,
    [FromWorkflowLevelId] INT           NULL,
    [ToWorkflowLevelId]   INT           NULL,
    [ApprovalStatusId]    INT           NOT NULL,
    [RequestStaffId]      INT           NOT NULL,
    [ResponseStaffId]     INT           NULL,
    [ArrivalDate]         DATETIME      NOT NULL,
    [ActualArrivalDate]   DATETIME      NULL,
    [ResponseDate]        DATETIME      NULL,
    [CompanyId]           INT           NOT NULL,
    [Comment]             VARCHAR (MAX) NULL,
    [Active]              BIT           NULL,
    [Deleted]             BIT           NULL,
    [CreatedBy]           VARCHAR (50)  NULL,
    [CreatedOn]           DATETIME      NULL,
    [UpdatedBy]           VARCHAR (50)  NULL,
    [UpdatedOn]           DATETIME      NULL,
    CONSTRAINT [PK_cor_workflowtrail] PRIMARY KEY CLUSTERED ([WorkflowTrailId] ASC),
    CONSTRAINT [FK_cor_workflowtrail_cor_approvalstatus] FOREIGN KEY ([ApprovalStatusId]) REFERENCES [dbo].[cor_approvalstatus] ([ApprovalStatusId]),
    CONSTRAINT [FK_cor_workflowtrail_cor_staff] FOREIGN KEY ([RequestStaffId]) REFERENCES [dbo].[cor_staff] ([StaffId]),
    CONSTRAINT [FK_cor_workflowtrail_cor_staff1] FOREIGN KEY ([ResponseStaffId]) REFERENCES [dbo].[cor_staff] ([StaffId]),
    CONSTRAINT [FK_cor_workflowtrail_cor_workflowlevel] FOREIGN KEY ([ToWorkflowLevelId]) REFERENCES [dbo].[cor_workflowlevel] ([WorkflowLevelId]),
    CONSTRAINT [FK_cor_workflowtrail_cor_workflowlevel1] FOREIGN KEY ([FromWorkflowLevelId]) REFERENCES [dbo].[cor_workflowlevel] ([WorkflowLevelId])
);

