CREATE TABLE [dbo].[credit_loancustomer] (
    [CustomerId]            INT           IDENTITY (1, 1) NOT NULL,
    [CustomerTypeId]        INT           NOT NULL,
    [TitleId]               INT           NULL,
    [FirstName]             VARCHAR (100) NOT NULL,
    [LastName]              VARCHAR (100) NULL,
    [MiddleName]            VARCHAR (100) NULL,
    [GenderId]              INT           NULL,
    [DOB]                   DATE          NULL,
    [Address]               VARCHAR (550) NOT NULL,
    [PostaAddress]          VARCHAR (550) NULL,
    [CityId]                INT           NULL,
    [Occupation]            VARCHAR (150) NULL,
    [EmploymentType]        INT           NULL,
    [PoliticallyExposed]    BIT           NULL,
    [CompanyName]           VARCHAR (250) NULL,
    [CompanyWebsite]        VARCHAR (250) NULL,
    [Email]                 VARCHAR (50)  NOT NULL,
    [PhoneNo]               VARCHAR (50)  NOT NULL,
    [RegistrationNo]        VARCHAR (50)  NULL,
    [CountryId]             INT           NULL,
    [Industry]              VARCHAR (250) NULL,
    [IncorporationCountry]  VARCHAR (250) NULL,
    [AnnualTurnover]        MONEY         NULL,
    [ShareholderFund]       MONEY         NULL,
    [ApprovalStatusId]      INT           NOT NULL,
    [MaritalStatusId]       INT           NULL,
    [CASAAccountNumber]     VARCHAR (50)  NULL,
    [RelationshipManagerId] INT           NULL,
    [Active]                BIT           NULL,
    [Deleted]               BIT           NULL,
    [CreatedBy]             VARCHAR (50)  NULL,
    [CreatedOn]             DATETIME      NULL,
    [UpdatedBy]             VARCHAR (50)  NULL,
    [UpdatedOn]             DATETIME      NULL,
    CONSTRAINT [PK_credit_loancustomer] PRIMARY KEY CLUSTERED ([CustomerId] ASC),
    CONSTRAINT [FK_credit_loancustomer_cor_approvalstatus] FOREIGN KEY ([ApprovalStatusId]) REFERENCES [dbo].[cor_approvalstatus] ([ApprovalStatusId]),
    CONSTRAINT [FK_credit_loancustomer_cor_city] FOREIGN KEY ([CityId]) REFERENCES [dbo].[cor_city] ([CityId]),
    CONSTRAINT [FK_credit_loancustomer_cor_country] FOREIGN KEY ([CountryId]) REFERENCES [dbo].[cor_country] ([CountryId]),
    CONSTRAINT [FK_credit_loancustomer_cor_customertype] FOREIGN KEY ([CustomerTypeId]) REFERENCES [dbo].[cor_customertype] ([CustomerTypeId]),
    CONSTRAINT [FK_credit_loancustomer_cor_employertype] FOREIGN KEY ([EmploymentType]) REFERENCES [dbo].[cor_employertype] ([EmployerTypeId]),
    CONSTRAINT [FK_credit_loancustomer_cor_gender] FOREIGN KEY ([GenderId]) REFERENCES [dbo].[cor_gender] ([GenderId]),
    CONSTRAINT [FK_credit_loancustomer_cor_maritalstatus] FOREIGN KEY ([MaritalStatusId]) REFERENCES [dbo].[cor_maritalstatus] ([MaritalStatusId]),
    CONSTRAINT [FK_credit_loancustomer_cor_title] FOREIGN KEY ([TitleId]) REFERENCES [dbo].[cor_title] ([TitleId])
);

