CREATE TABLE [dbo].[credit_loanscheduleperiodic] (
    [LoanSchedulePeriodicId]         INT          IDENTITY (1, 1) NOT NULL,
    [LoanId]                         INT          NOT NULL,
    [PaymentNumber]                  INT          NOT NULL,
    [PaymentDate]                    DATE         NOT NULL,
    [StartPrincipalAmount]           MONEY        NOT NULL,
    [PeriodPaymentAmount]            MONEY        NOT NULL,
    [PeriodInterestAmount]           MONEY        NOT NULL,
    [PeriodPrincipalAmount]          MONEY        NOT NULL,
    [ClosingBalance]                 MONEY        NOT NULL,
    [EndPrincipalAmount]             MONEY        NOT NULL,
    [InterestRate]                   FLOAT (53)   NOT NULL,
    [AmortisedStartPrincipalAmount]  MONEY        NOT NULL,
    [AmortisedPeriodPaymentAmount]   MONEY        NOT NULL,
    [AmortisedPeriodInterestAmount]  MONEY        NOT NULL,
    [AmortisedPeriodPrincipalAmount] MONEY        NOT NULL,
    [AmortisedClosingBalance]        MONEY        NOT NULL,
    [AmortisedEndPrincipalAmount]    MONEY        NOT NULL,
    [EffectiveInterestRate]          FLOAT (53)   NOT NULL,
    [StaffId]                        INT          NULL,
    [Active]                         BIT          NOT NULL,
    [Deleted]                        BIT          NULL,
    [CreatedBy]                      VARCHAR (50) NULL,
    [CreatedOn]                      DATETIME     NULL,
    [UpdatedBy]                      VARCHAR (50) NULL,
    [UpdatedOn]                      DATETIME     NULL,
    CONSTRAINT [PK_credit_loanscheduleperiodic] PRIMARY KEY CLUSTERED ([LoanSchedulePeriodicId] ASC)
);

