CREATE TABLE [dbo].[credit_lgd_historyinformation] (
    [HistoricalLGDId]     INT           IDENTITY (1, 1) NOT NULL,
    [LoanAmount]          MONEY         NOT NULL,
    [CustomerName]        VARCHAR (250) NULL,
    [LoanReferenceNumber] VARCHAR (250) NULL,
    [ProductCode]         VARCHAR (250) NULL,
    [ProductName]         VARCHAR (250) NULL,
    [EffectiveDate]       DATETIME      NULL,
    [MaturityDate]        DATETIME      NULL,
    [CR]                  FLOAT (53)    NULL,
    [EIR]                 FLOAT (53)    NULL,
    [Frequency]           VARCHAR (50)  NULL,
    [Field1]              MONEY         NULL,
    [Field2]              MONEY         NULL,
    [Field3]              MONEY         NULL,
    [Field4]              MONEY         NULL,
    [Field5]              MONEY         NULL,
    [Field6]              MONEY         NULL,
    [Field7]              MONEY         NULL,
    [Field8]              MONEY         NULL,
    [Field9]              MONEY         NULL,
    [Field10]             MONEY         NULL,
    [Field11]             MONEY         NULL,
    [Field12]             MONEY         NULL,
    [Field13]             MONEY         NULL,
    [Field14]             MONEY         NULL,
    [Field15]             MONEY         NULL,
    [Field16]             MONEY         NULL,
    [Field17]             MONEY         NULL,
    [Field18]             MONEY         NULL,
    [Field19]             MONEY         NULL,
    [Field20]             MONEY         NULL,
    [Field21]             MONEY         NULL,
    [Field22]             MONEY         NULL,
    [Field23]             MONEY         NULL,
    [Field24]             MONEY         NULL,
    [Field25]             MONEY         NULL,
    [Field26]             MONEY         NULL,
    [Field27]             MONEY         NULL,
    [Field28]             MONEY         NULL,
    [Field29]             MONEY         NULL,
    [Field30]             MONEY         NULL,
    [Field31]             MONEY         NULL,
    [Field32]             MONEY         NULL,
    [Field33]             MONEY         NULL,
    [Field34]             MONEY         NULL,
    [Field35]             MONEY         NULL,
    [Field36]             MONEY         NULL,
    [Field37]             MONEY         NULL,
    [Field38]             MONEY         NULL,
    [Field39]             MONEY         NULL,
    [Field40]             MONEY         NULL,
    [Field41]             MONEY         NULL,
    [Field42]             MONEY         NULL,
    [Field43]             MONEY         NULL,
    [Field44]             MONEY         NULL,
    [Field45]             MONEY         NULL,
    [Field46]             MONEY         NULL,
    [Field47]             MONEY         NULL,
    [Field48]             MONEY         NULL,
    [Field49]             MONEY         NULL,
    [Field50]             MONEY         NULL,
    [Field51]             MONEY         NULL,
    [Field52]             MONEY         NULL,
    [Field53]             MONEY         NULL,
    [Field54]             MONEY         NULL,
    [Field55]             MONEY         NULL,
    [Field56]             MONEY         NULL,
    [Field57]             MONEY         NULL,
    [Field58]             MONEY         NULL,
    [Field59]             MONEY         NULL,
    [Field60]             MONEY         NULL,
    [Field61]             MONEY         NULL,
    [Active]              BIT           NULL,
    [Deleted]             BIT           NULL,
    [CreatedBy]           VARCHAR (50)  NULL,
    [CreatedOn]           DATETIME      NULL,
    [UpdatedBy]           VARCHAR (50)  NULL,
    [UpdatedOn]           DATETIME      NULL,
    CONSTRAINT [PK_credit_lgd_historyinformation] PRIMARY KEY CLUSTERED ([HistoricalLGDId] ASC)
);

