CREATE TABLE [dbo].[credit_loanscheduledailyarchive] (
    [LoanScheduleDailyArchiveId]    INT           IDENTITY (1, 1) NOT NULL,
    [ArchiveDate]                   DATE          NOT NULL,
    [ArchiveBatchCode]              VARCHAR (250) NULL,
    [LoanId]                        INT           NOT NULL,
    [PaymentNumber]                 INT           NOT NULL,
    [Date]                          DATE          NOT NULL,
    [PaymentDate]                   DATE          NOT NULL,
    [OpeningBalance]                MONEY         NOT NULL,
    [StartPrincipalAmount]          MONEY         NOT NULL,
    [DailyPaymentAmount]            MONEY         NOT NULL,
    [DailyInterestAmount]           MONEY         NOT NULL,
    [DailyPrincipalAmount]          MONEY         NOT NULL,
    [ClosingBalance]                MONEY         NOT NULL,
    [EndPrincipalAmount]            MONEY         NOT NULL,
    [AccruedInterest]               MONEY         NOT NULL,
    [AmortisedCost]                 MONEY         NOT NULL,
    [InterestRate]                  FLOAT (53)    NOT NULL,
    [AmortisedOpeningBalance]       MONEY         NOT NULL,
    [AmortisedStartPrincipalAmount] MONEY         NOT NULL,
    [AmortisedDailyPaymentAmount]   MONEY         NOT NULL,
    [AmortisedDailyInterestAmount]  MONEY         NOT NULL,
    [AmortisedDailyPrincipalAmount] MONEY         NOT NULL,
    [AmortisedClosingBalance]       MONEY         NOT NULL,
    [AmortisedEndPrincipalAmount]   MONEY         NOT NULL,
    [AmortisedAccruedInterest]      MONEY         NOT NULL,
    [Amortised_AmortisedCost]       MONEY         NOT NULL,
    [UnearnedFee]                   MONEY         NOT NULL,
    [EarnedFee]                     MONEY         NOT NULL,
    [EffectiveInterestRate]         FLOAT (53)    NOT NULL,
    [StaffId]                       INT           NULL,
    [Active]                        BIT           NOT NULL,
    [Deleted]                       BIT           NULL,
    [CreatedBy]                     VARCHAR (50)  NULL,
    [CreatedOn]                     DATETIME      NULL,
    [UpdatedBy]                     VARCHAR (50)  NULL,
    [UpdatedOn]                     DATETIME      NULL,
    CONSTRAINT [PK_credit_loanscheduledailyarchive] PRIMARY KEY CLUSTERED ([LoanScheduleDailyArchiveId] ASC)
);

