CREATE TABLE [dbo].[credit_corporateapplicationscorecard] (
    [ApplicationScoreCardId] INT             IDENTITY (1, 1) NOT NULL,
    [LoanApplicationId]      INT             NOT NULL,
    [CustomerId]             INT             NOT NULL,
    [ProductId]              INT             NOT NULL,
    [Field1]                 DECIMAL (18, 4) NULL,
    [Field2]                 DECIMAL (18, 4) NULL,
    [Field3]                 DECIMAL (18, 4) NULL,
    [Field4]                 DECIMAL (18, 4) NULL,
    [Field5]                 DECIMAL (18, 4) NULL,
    [Field6]                 DECIMAL (18, 4) NULL,
    [Field7]                 DECIMAL (18, 4) NULL,
    [Field8]                 DECIMAL (18, 4) NULL,
    [Field9]                 DECIMAL (18, 4) NULL,
    [Field10]                DECIMAL (18, 4) NULL,
    [Field11]                DECIMAL (18, 4) NULL,
    [Field12]                DECIMAL (18, 4) NULL,
    [Field13]                DECIMAL (18, 4) NULL,
    [Field14]                DECIMAL (18, 4) NULL,
    [Field15]                DECIMAL (18, 4) NULL,
    [Field16]                DECIMAL (18, 4) NULL,
    [Field17]                DECIMAL (18, 4) NULL,
    [Field18]                DECIMAL (18, 4) NULL,
    [Field19]                DECIMAL (18, 4) NULL,
    [Field20]                DECIMAL (18, 4) NULL,
    [Field21]                DECIMAL (18, 4) NULL,
    [Field22]                DECIMAL (18, 4) NULL,
    [Field23]                DECIMAL (18, 4) NULL,
    [Field24]                DECIMAL (18, 4) NULL,
    [Field25]                DECIMAL (18, 4) NULL,
    [Field26]                DECIMAL (18, 4) NULL,
    [Field27]                DECIMAL (18, 4) NULL,
    [Field28]                DECIMAL (18, 4) NULL,
    [Field29]                DECIMAL (18, 4) NULL,
    [Field30]                DECIMAL (18, 4) NULL,
    [Active]                 BIT             NULL,
    [Deleted]                BIT             NULL,
    [CreatedBy]              VARCHAR (50)    NULL,
    [CreatedOn]              DATETIME        NULL,
    [UpdatedBy]              VARCHAR (50)    NULL,
    [UpdatedOn]              DATETIME        NULL,
    CONSTRAINT [PK_credit_corporateapplicationscorecard] PRIMARY KEY CLUSTERED ([ApplicationScoreCardId] ASC),
    CONSTRAINT [FK_credit_corporateapplicationscorecard_credit_loanapplication] FOREIGN KEY ([LoanApplicationId]) REFERENCES [dbo].[credit_loanapplication] ([LoanApplicationId]),
    CONSTRAINT [FK_credit_corporateapplicationscorecard_credit_loancustomer] FOREIGN KEY ([CustomerId]) REFERENCES [dbo].[credit_loancustomer] ([CustomerId]),
    CONSTRAINT [FK_credit_corporateapplicationscorecard_credit_product] FOREIGN KEY ([ProductId]) REFERENCES [dbo].[credit_product] ([ProductId])
);

