CREATE TABLE [dbo].[credit_loanreviewoperation] (
    [LoanReviewOperationId]        INT           IDENTITY (1, 1) NOT NULL,
    [LoanId]                       INT           NOT NULL,
    [ProductId]                    INT           NOT NULL,
    [OperationId]                  INT           NOT NULL,
    [EffectiveDate]                DATE          NOT NULL,
    [Comment]                      VARCHAR (MAX) COLLATE Latin1_General_CI_AS NOT NULL,
    [InterestRate]                 FLOAT (53)    NULL,
    [Prepayment]                   MONEY         NULL,
    [PrincipalFrequencyTypeId]     INT           NULL,
    [InterestFrequencyTypeId]      INT           NULL,
    [PrincipalFirstPaymentDate]    DATE          NULL,
    [InterestFirstPaymentDate]     DATE          NULL,
    [MaturityDate]                 DATE          NULL,
    [Tenor]                        INT           NULL,
    [CASA_AccountId]               INT           NULL,
    [OverDraftTopUp]               MONEY         NULL,
    [FeeCharges]                   MONEY         NULL,
    [ScheduleTypeId]               INT           NULL,
    [ScheduleDayCountConventionId] INT           NULL,
    [SchedultDayInterestTypeId]    INT           NULL,
    [ApprovalStatusId]             INT           NOT NULL,
    [IsManagementInterest]         BIT           CONSTRAINT [DF_Table_1_ISMANAGEMENTINTERESTRATE] DEFAULT ((0)) NOT NULL,
    [OperationComleted]            BIT           CONSTRAINT [DF_Table_1_OPERATIONCOMPLETED] DEFAULT ((0)) NOT NULL,
    [Active]                       BIT           NULL,
    [Deleted]                      BIT           NULL,
    [CreatedBy]                    VARCHAR (50)  NULL,
    [CreatedOn]                    DATETIME      NULL,
    [UpdatedBy]                    VARCHAR (50)  NULL,
    [UpdatedOn]                    DATETIME      NULL,
    CONSTRAINT [PK_credit_loanreviewoperation] PRIMARY KEY CLUSTERED ([LoanReviewOperationId] ASC)
);

