CREATE TABLE [dbo].[credit_loanapplication] (
    [LoanApplicationId]       INT              IDENTITY (1, 1) NOT NULL,
    [CustomerId]              INT              NOT NULL,
    [ProposedProductId]       INT              NOT NULL,
    [ProposedTenor]           INT              NOT NULL,
    [ProposedRate]            FLOAT (53)       NOT NULL,
    [ProposedAmount]          MONEY            NOT NULL,
    [ApprovedProductId]       INT              NOT NULL,
    [ApprovedTenor]           INT              NOT NULL,
    [ApprovedRate]            FLOAT (53)       NOT NULL,
    [ApprovedAmount]          MONEY            NOT NULL,
    [CurrencyId]              INT              NOT NULL,
    [ExchangeRate]            FLOAT (53)       NOT NULL,
    [ApprovalStatusId]        INT              NOT NULL,
    [HasDoneChecklist]        BIT              NOT NULL,
    [ApplicationDate]         DATE             NOT NULL,
    [EffectiveDate]           DATE             NOT NULL,
    [MaturityDate]            DATE             NOT NULL,
    [FirstPrincipalDate]      DATE             NULL,
    [FirstInterestDate]       DATE             NULL,
    [LoanApplicationStatusId] INT              NULL,
    [CompanyId]               INT              NULL,
    [ApplicationRefNumber]    VARCHAR (50)     NOT NULL,
    [Score]                   DECIMAL (18, 2)  NULL,
    [PD]                      DECIMAL (36, 26) NULL,
    [GenerateOfferLetter]     BIT              CONSTRAINT [DF_credit_loanapplication_GenerateOfferLetter] DEFAULT ((0)) NOT NULL,
    [Purpose]                 VARCHAR (2000)   NULL,
    [Active]                  BIT              NOT NULL,
    [Deleted]                 BIT              NULL,
    [CreatedBy]               VARCHAR (50)     NULL,
    [CreatedOn]               DATETIME         NULL,
    [UpdatedBy]               VARCHAR (50)     NULL,
    [UpdatedOn]               DATETIME         NULL,
    CONSTRAINT [PK_credit_loanapplication] PRIMARY KEY CLUSTERED ([LoanApplicationId] ASC),
    CONSTRAINT [FK_credit_loanapplication_cor_approvalstatus] FOREIGN KEY ([ApprovalStatusId]) REFERENCES [dbo].[cor_approvalstatus] ([ApprovalStatusId]),
    CONSTRAINT [FK_credit_loanapplication_cor_company] FOREIGN KEY ([CompanyId]) REFERENCES [dbo].[cor_company] ([CompanyId]),
    CONSTRAINT [FK_credit_loanapplication_cor_currency] FOREIGN KEY ([CurrencyId]) REFERENCES [dbo].[cor_currency] ([CurrencyId]),
    CONSTRAINT [FK_credit_loanapplication_credit_loancustomer] FOREIGN KEY ([CustomerId]) REFERENCES [dbo].[credit_loancustomer] ([CustomerId]),
    CONSTRAINT [FK_credit_loanapplication_credit_product] FOREIGN KEY ([ProposedProductId]) REFERENCES [dbo].[credit_product] ([ProductId]),
    CONSTRAINT [FK_credit_loanapplication_credit_product1] FOREIGN KEY ([ApprovedProductId]) REFERENCES [dbo].[credit_product] ([ProductId])
);

