CREATE TABLE [dbo].[credit_product] (
    [ProductId]                   INT             IDENTITY (1, 1) NOT NULL,
    [ProductCode]                 VARCHAR (50)    NOT NULL,
    [ProductName]                 VARCHAR (250)   NOT NULL,
    [PaymentType]                 INT             NOT NULL,
    [CollateralRequired]          BIT             NOT NULL,
    [QuotedInstrument]            BIT             NOT NULL,
    [Rate]                        FLOAT (53)      NOT NULL,
    [LateRepayment]               BIT             NOT NULL,
    [Period]                      INT             NULL,
    [CleanUpCircle]               INT             NULL,
    [WeightedMaxScore]            DECIMAL (18, 4) NULL,
    [Default]                     INT             NULL,
    [DefaultRange]                INT             NULL,
    [Significant2]                DECIMAL (18, 4) NULL,
    [Significant3]                DECIMAL (18, 4) NULL,
    [ProductTypeId]               INT             NULL,
    [PrincipalGL]                 INT             NULL,
    [InterestIncomeExpenseGL]     INT             NULL,
    [InterestReceivablePayableGL] INT             NULL,
    [FrequencyTypeId]             INT             NULL,
    [TenorInDays]                 INT             NULL,
    [ScheduleTypeId]              INT             NULL,
    [CollateralPercentage]        DECIMAL (18, 4) CONSTRAINT [DF_credit_product_CollateralPercentage] DEFAULT ((0)) NULL,
    [ProductLimit]                DECIMAL (18, 2) NULL,
    [LateTerminationCharge]       FLOAT (53)      NULL,
    [EarlyTerminationCharge]      FLOAT (53)      NULL,
    [LowRiskDefinition]           FLOAT (53)      NULL,
    [Active]                      BIT             NULL,
    [Deleted]                     BIT             NULL,
    [CreatedBy]                   VARCHAR (50)    NULL,
    [CreatedOn]                   DATETIME        NULL,
    [UpdatedBy]                   VARCHAR (50)    NULL,
    [UpdatedOn]                   DATETIME        NULL,
    CONSTRAINT [PK_credit_product] PRIMARY KEY CLUSTERED ([ProductId] ASC),
    CONSTRAINT [FK_credit_product_credit_repaymenttype] FOREIGN KEY ([PaymentType]) REFERENCES [dbo].[credit_repaymenttype] ([RepaymentTypeId])
);

