CREATE TABLE [dbo].[credit_casa] (
    [CasaAccountId]              INT             IDENTITY (1, 1) NOT NULL,
    [AccountNumber]              VARCHAR (50)    NOT NULL,
    [AccountName]                VARCHAR (100)   NOT NULL,
    [CustomerId]                 INT             NOT NULL,
    [ProductId]                  INT             NOT NULL,
    [CompanyId]                  INT             NOT NULL,
    [BranchId]                   INT             NOT NULL,
    [CurrencyId]                 INT             NOT NULL,
    [IsCurrentAccount]           BIT             NOT NULL,
    [Tenor]                      INT             NULL,
    [InterestRate]               DECIMAL (18, 2) NULL,
    [EffectiveDate]              DATE            NULL,
    [TerminalDate]               DATE            NULL,
    [ActionBy]                   INT             NULL,
    [ActionDate]                 DATETIME        NULL,
    [AccountStatusId]            INT             NOT NULL,
    [OperationId]                INT             NULL,
    [AvailableBalance]           MONEY           NOT NULL,
    [LedgerBalance]              MONEY           NOT NULL,
    [RelationshipOfficerId]      INT             NULL,
    [RelationshipManagerId]      INT             NULL,
    [MISCode]                    VARCHAR (50)    NULL,
    [TEAMMISCode]                VARCHAR (50)    NULL,
    [OverdraftAmount]            MONEY           NULL,
    [OverdraftInterestRate]      MONEY           NULL,
    [OverdraftExpiryDate]        DATE            NULL,
    [HasOverdraft]               BIT             NULL,
    [LienAmount]                 MONEY           NOT NULL,
    [HasLien]                    BIT             NOT NULL,
    [PostNoStatusId]             INT             NULL,
    [OldAccountNumber1]          VARCHAR (50)    NULL,
    [OldAccountNumber2]          VARCHAR (50)    NULL,
    [OldAccountNumber3]          VARCHAR (50)    NULL,
    [AprovalStatusId]            INT             NULL,
    [CustomerSensitivityLevelId] INT             NULL,
    [FromDeposit]                BIT             NULL,
    [Active]                     BIT             NULL,
    [Deleted]                    BIT             NULL,
    [CreatedBy]                  VARCHAR (50)    NULL,
    [CreatedOn]                  DATETIME        NULL,
    [UpdatedBy]                  VARCHAR (50)    NULL,
    [UpdatedOn]                  DATETIME        NULL,
    CONSTRAINT [PK_credit_casa] PRIMARY KEY CLUSTERED ([CasaAccountId] ASC),
    CONSTRAINT [IX_credit_casa_Unique] UNIQUE NONCLUSTERED ([AccountNumber] ASC, [CompanyId] ASC)
);

