CREATE TABLE [dbo].[deposit_bankclosure] (
    [BankClosureId]    INT             IDENTITY (1, 1) NOT NULL,
    [Structure]        INT             NULL,
    [SubStructure]     INT             NULL,
    [AccountName]      VARCHAR (50)    NULL,
    [AccountNumber]    VARCHAR (50)    NULL,
    [Status]           BIT             NULL,
    [AccountBalance]   VARCHAR (50)    NULL,
    [Currency]         INT             NULL,
    [ClosingDate]      DATE            NULL,
    [Reason]           VARCHAR (50)    NULL,
    [Charges]          DECIMAL (18, 2) NULL,
    [FinalSettlement]  VARCHAR (50)    NULL,
    [Beneficiary]      VARCHAR (50)    NULL,
    [ModeOfSettlement] BIT             NULL,
    [TransferAccount]  VARCHAR (50)    NULL,
    [ApproverName]     VARCHAR (50)    NULL,
    [ApproverComment]  VARCHAR (50)    NULL,
    [Active]           BIT             NULL,
    [Deleted]          BIT             NULL,
    [CreatedBy]        VARCHAR (50)    NULL,
    [CreatedOn]        DATETIME        NULL,
    [UpdatedBy]        VARCHAR (50)    NULL,
    [UpdatedOn]        DATETIME        NULL,
    CONSTRAINT [PK_deposit_bankclosure] PRIMARY KEY CLUSTERED ([BankClosureId] ASC)
);

