CREATE TABLE [dbo].[deposit_accountopening] (
    [CustomerId]            INT             IDENTITY (1, 1) NOT NULL,
    [CustomerTypeId]        INT             NOT NULL,
    [AccountTypeId]         INT             NOT NULL,
    [AccountCategoryId]     INT             NULL,
    [CurrencyId]            INT             NOT NULL,
    [AccountNumber]         VARCHAR (50)    NULL,
    [Title]                 INT             NULL,
    [Surname]               VARCHAR (50)    NULL,
    [Firstname]             VARCHAR (50)    NULL,
    [Othername]             VARCHAR (50)    NULL,
    [MaritalStatusId]       INT             NULL,
    [GenderId]              INT             NULL,
    [BirthCountryId]        INT             NULL,
    [DOB]                   DATE            NULL,
    [MotherMaidenName]      VARCHAR (50)    NULL,
    [RelationshipOfficerId] INT             NULL,
    [TaxIDNumber]           VARCHAR (500)   NULL,
    [BVN]                   VARCHAR (500)   NULL,
    [Nationality]           INT             NULL,
    [ResidentPermitNumber]  VARCHAR (50)    NULL,
    [PermitIssueDate]       DATE            NULL,
    [PermitExpiryDate]      DATE            NULL,
    [SocialSecurityNumber]  VARCHAR (50)    NULL,
    [StateOfOrigin]         INT             NULL,
    [LocalGovernment]       INT             NULL,
    [ResidentOfCountry]     BIT             NULL,
    [Address1]              VARCHAR (50)    NULL,
    [Address2]              VARCHAR (50)    NULL,
    [City]                  VARCHAR (50)    NULL,
    [StateId]               INT             NULL,
    [CountryId]             INT             NULL,
    [Email]                 VARCHAR (50)    NULL,
    [MailingAddress]        VARCHAR (50)    NULL,
    [MobileNumber]          VARCHAR (50)    NULL,
    [InternetBanking]       BIT             NULL,
    [EmailStatement]        BIT             NULL,
    [Card]                  BIT             NULL,
    [SmsAlert]              BIT             NULL,
    [EmailAlert]            BIT             NULL,
    [Token]                 BIT             NULL,
    [EmploymentType]        INT             NULL,
    [EmployerName]          VARCHAR (50)    NULL,
    [EmployerAddress]       VARCHAR (50)    NULL,
    [EmployerState]         VARCHAR (50)    NULL,
    [Occupation]            VARCHAR (50)    NULL,
    [BusinessName]          VARCHAR (50)    NULL,
    [BusinessAddress]       VARCHAR (50)    NULL,
    [BusinessState]         VARCHAR (50)    NULL,
    [JobTitle]              VARCHAR (50)    NULL,
    [Other]                 VARCHAR (50)    NULL,
    [DeclarationDate]       DATE            NULL,
    [DeclarationCompleted]  BIT             NULL,
    [SignatureUpload]       VARBINARY (MAX) NULL,
    [SoleSignatory]         INT             NULL,
    [MaxNoOfSignatory]      INT             NULL,
    [RegistrationNumber]    VARCHAR (50)    NULL,
    [Industry]              VARCHAR (50)    NULL,
    [Jurisdiction]          VARCHAR (50)    NULL,
    [Website]               VARCHAR (50)    NULL,
    [NatureOfBusiness]      VARCHAR (50)    NULL,
    [AnnualRevenue]         VARCHAR (50)    NULL,
    [IsStockExchange]       BIT             NULL,
    [Stock]                 VARCHAR (50)    NULL,
    [RegisteredAddress]     VARCHAR (50)    NULL,
    [ScumlNumber]           VARCHAR (50)    NULL,
    [Active]                BIT             NULL,
    [Deleted]               BIT             NULL,
    [CreatedBy]             VARCHAR (50)    NULL,
    [CreatedOn]             DATETIME        NULL,
    [UpdatedBy]             VARCHAR (50)    NULL,
    [UpdatedOn]             DATETIME        NULL,
    CONSTRAINT [PK_deposit_accountopening] PRIMARY KEY CLUSTERED ([CustomerId] ASC)
);

