CREATE TABLE [dbo].[ifrs_var_coeff_comp_pd] (
    [Id]                  INT          IDENTITY (1, 1) NOT NULL,
    [Intercept]           FLOAT (53)   NULL,
    [coeff1]              FLOAT (53)   NULL,
    [coeff2]              FLOAT (53)   NULL,
    [coeff3]              FLOAT (53)   NULL,
    [coeff4]              FLOAT (53)   NULL,
    [coeff5]              FLOAT (53)   NULL,
    [coeff6]              FLOAT (53)   NULL,
    [coeff7]              FLOAT (53)   NULL,
    [Macro_Var1]          FLOAT (53)   NULL,
    [Macro_var2]          FLOAT (53)   NULL,
    [Macro_var3]          FLOAT (53)   NULL,
    [Macro_var4]          FLOAT (53)   NULL,
    [Macro_var5]          FLOAT (53)   NULL,
    [Macro_var6]          FLOAT (53)   NULL,
    [Macro_var7]          FLOAT (53)   NULL,
    [PD_Computed]         FLOAT (53)   NULL,
    [ProductCode]         VARCHAR (50) NULL,
    [LoanReferenceNumber] VARCHAR (50) NULL,
    [Year]                INT          NULL,
    [CompanyCode]         VARCHAR (50) NULL,
    [RunDate]             DATETIME     NULL,
    [Active]              BIT          NULL,
    [Deleted]             BIT          NULL,
    [CreatedOn]           DATE         NULL,
    [Createdby]           VARCHAR (50) NULL,
    [UpdatedBy]           VARCHAR (50) NULL,
    [UpdatedOn]           DATE         NULL
);

